### ISSUE TITLE
Fix 400 error on empty search query

### ISSUE THREAD

**Issue by Loskir** [Loskir/price-monitor-website-next#2]

**Comment by fishtriangle** [comment]
Hello, try to solve it.

**Comment by Loskir** [comment]
Hello! I think it should be fixed from the backend side. It should return [] or maybe some featured products in this case

**Comment by fishtriangle** [comment]
ok, i thought to disable useQuary when input is empty. And maybe add debounce

**Comment by Loskir** [comment]
Fixed in api
